# Copyright (c) 2024 Purple Clay
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# in the Software without restriction, including without limitation the rights
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: dagger-cli
on:
  push:
    branches:
      - main
    paths:
      - "apko.yaml"
  workflow_dispatch:

permissions:
  actions: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Grep Dagger Version
        id: dagger_version
        run: |
          DAGGER_VERSION=$(grep -Eo 'dagger=(.*)' apko.yaml | cut -d'=' -f2)
          echo "DAGGER_VERSION=${DAGGER_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Publish Dagger CLI
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: github.com/purpleclay/daggerverse/apko@v0.3.1
          args: load --cfg apko.yaml publish --registry "${{ env.REGISTRY }}" --username "${{ github.repository_owner }}" --password env:GITHUB_TOKEN --ref "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.dagger_version.outputs.DAGGER_VERSION }}"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.12.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
